
# 👨‍💻 Lucas de Morais

Especialista em Segurança da Informação | Pentester | Bug Bounty Hunter | Desenvolvedor
---
🎯 **Resumo Profissional**  
Profissional com ampla experiência em **Segurança da Informação**, com foco em:
- Testes de Invasão (Pentest)
- Análise de Vulnerabilidades
- Segurança Ofensiva e Defensiva
- Forense Computacional
- Desenvolvimento de Ferramentas Personalizadas
- Espionagem e Contraespionagem Cibernética

Atuo como **Bug Bounty Hunter**, consultor, líder de segurança corporativa (CSO) e desenvolvedor de soluções de automação para ambientes Linux/Kali via Termux.
---
🧠 **Certificações**  
- Offensive Security: OSCP, OSCE, OSWP, OSEP  
- EC-Council: CEH, CHFI, ECSA, ENSA, LPT  
- CompTIA: Security+, Pentest+  
- Cisco: CCNA Security, CCSP, CCIP  
- ISACA: CISM, CISA  
- (ISC)²: CISSP, CSSLP, ISSAP, ISSEP, ISSMP, SSCP, CAP  
- ISECOM: OPSA, OPST  
---
🧰 **Tecnologias e Ferramentas**  
- Kali Linux (Termux)
- Metasploit, BeEF, Wireshark, Aircrack-ng
- Apktool, OWASP ZAP, Wapiti, Nikto, Hydra, John The Ripper
- Ferramentas próprias: scripts ofensivos automatizados, análise de endpoints web, obfuscação JS, exploits (EternalBlue, Shellshock), pós-exploração com Volatility
- Integração com Playwright e automação ofensiva de browsers headless

---

🔧 **Automação e Desenvolvimento**  
Criação de scripts Bash e ferramentas modulares para:
- Coleta de informações
- Varredura e exploração de vulnerabilidades
- Engenharia social automatizada
- Geração de relatórios com Lynis
- Empacotamento `.deb` para distribuição em ambientes Debian-based
---
💼 **Serviços Oferecidos**  
- Pentests internos e externos  
- Consultoria de segurança sob demanda  
- Monitoramento e resposta a incidentes  
- Desenvolvimento de ferramentas sob medida  
- Treinamentos em segurança ofensiva
---
📩 **Contato**  
- 📧 lucasescobarmorais@gmail.com  
- 📱 +55 (62) 98245-6245  
---
🧠 **Sobre Mim**  
Tenho **Síndrome de Asperger**, com hiperfoco, lógica crítica e sensibilidade sensorial elevada. Minha dedicação intensa à tecnologia me permite entregar soluções robustas, eficazes e inovadoras, sempre buscando excelência técnica e ética profissional.
---
🛡️ *“Segurança não é um produto, é um processo.”*
